# ==========================================
# SafeVault Configuration
# ==========================================

SOURCE_FOLDER="ProjectFiles"
BACKUP_FOLDER="backups"
RESTORE_FOLDER="restore"
LOG_FOLDER="logs"

BUCKET_NAME="safevault-backup-09072026-ma"

RETENTION_DAYS=30
LOG_FILE="backup.log"
